name: mediacrawler-proxy

services:
  squid:
    build:
      context: .
      dockerfile: Dockerfile
    image: mediacrawler/squid-proxy:latest
    container_name: mediacrawler_squid
    restart: unless-stopped
    ports:
      - "3128:3128"
    env_file:
      - .env
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
